sudo: required
language: perl6
perl6:
    - latest
install:
    - sudo apt-get install icecast2
    - sudo sed -i -e 's/ENABLE=false/ENABLE=true/' /etc/default/icecast2
    - sudo service icecast2 start
    - rakudobrew build-zef
    - zef --/test --deps-only install .
