name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: jonathanstowe/rakudo-liquidsoap:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Raku version
      run: raku -v

    - name: Install dependencies
      run: zef install --deps-only --/test --test-depends .

    # Not quite sure whether this is necessary in this image
    - name: Enable icecase
      run:  sed -i -e 's/ENABLE=false/ENABLE=true/' /etc/default/icecast2

    - name: Start Icecast
      run: service icecast2 start

    - name: Run tests
      run: zef test -v --debug .
